# Generated by Django 2.2 on 2020-06-02 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=30)),
                ('story_id', models.CharField(max_length=30)),
                ('points', models.PositiveIntegerField(default=0)),
                ('date_created', models.DateField(auto_now=True)),
                ('due_date', models.DateField()),
                ('type', models.CharField(choices=[('BUG', 'Bug'), ('RFE', 'RFE'), ('DOCUMENTATION', 'Documentation')], default='BUG', max_length=30)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.User')),
            ],
        ),
    ]
